### ISSUE TITLE
Drobnosti

### ISSUE THREAD

**Issue by mohlerit** [KaterinaProchazkova/cv-katerina-prochazkova#1]
Ahoj Kateřino,
jako suplent za Verču jsem se ti mrknl na tvůj kód. Musím říct, že se ti povedlo vytvořit krásnou stránku. Líbí se mi jak jsis s tím vyhrála a co jsi dokázala udělat.

Pokud ti nebude vadit mám tady pár tipů na zlepšení, ale nic z toho jak to máš není špatně.

První věcí je HTML a řádek dva. V tagu `html` je atribut `lang` s hodnotou `en`. Stránka je v češtině a tak je správně tuto hodnotu přepsat na `cs`.

V CSS kombinuješ zápis barev v RGB ( rgb(0, 0, 0) ) tak i v hexadecimálním zápise ( #000000 ). Není to špatně, ale kód vypadá čistěji, když používáš jeden tip zápisu. Mé OCD mě nutí ti říct, že hex zápis píšeš jak malými tak někdy velkými písmeny. Osobně jsme radši když je vše napsané malými písmeny, ale jak říkám to je mí OCD.

Přibližně od řádku 127 jsi už byla nejspíš unavená a koukám, že máš tam nějaké prázdné řádky a nebo odskočený text jinam. 

K tvé otázce v README.MD. Nejspíš je to jedno, protože je-li zadáno border-collapse: collapse, border-spacing je ignorován.
Jinak na tyto otázky založ příště issue. Bude to lepší.

Jak jsem říkal, tak se jendá o drobnosti a do classroom ti už letí hodnocení.

**Comment by KaterinaRadochova** [comment]
Ahoj Martine, 
děkuji za tvůj čas a připomínky, mám opraveno 😉
Máš pravdu, u barev se budu snažit psát jeden tip zápisu, vypadá to fakt blbě.
Možná unavená, ale zároveň nervózní z toho, jestli dokážu napsat to, co jsem si navrhla v XD 😂
Jsem ráda, že těch chyb moc nebylo, čekala jsem to horší.
Děkuju.
